server:
  port: 9010
spring:
  application:
    name: mypage
  datasource:
    url: jdbc:mysql://localhost:3306/mypage?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


mybatis:
  mapper-locations: classpath:mappers/*.xml
